version: 2.1
orbs:
  serverless: circleci/serverless-framework@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  aws-cli: circleci/aws-cli@0.1.22
  node: circleci/node@2.0

filters: &filters
  tags:
    only: /.*/
jobs:
  test-sls-install-versioned:
    executor: serverless/default
    environment:
      SLS_DEBUG: "1"
    steps:
      - checkout
      - serverless/setup:
          version: 3.15.0
          provider: ""
      - run:
          name: Check SLS version
          command: |
            serverless --version | grep 3.15.0

  test-sls-deploy:
    # Test within the default executor
    # - install the aws cli
    # - run serverless setup
    # - Test the node app
    # - deploy sample application
    executor: serverless/default
    environment:
      SLS_DEBUG: "1"
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages:
          app-dir: "~/project/example"
      - run:
          command: npm run test
          working_directory: "~/project/example"
      - serverless/setup:
          provider: AWS
      - run:
          name: Local invoke add function
          working_directory: "~/project/example"
          command: |
            serverless invoke local --function add --path 'sampleData/data.json'
      - run:
          working_directory: "~/project/example"
          command: ls && serverless deploy
          name: deploy
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test-sls-deploy:
          filters: *filters
          context: CPE_ORBS_AWS
      - test-sls-install-versioned:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/serverless-framework
          vcs-type: << pipeline.project.type >>
          github-token: GHI_TOKEN
          pub-type: production
          requires:
            - orb-tools/pack
            - test-sls-deploy
            - test-sls-install-versioned
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
