# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  A highly cached Python environment with included CI tools and NodeJS.
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: "3.7" #update to node version when possible.
    description: >
      Pick a specific cimg/python image variant with NodeJS installed:
      https://hub.docker.com/r/cimg/pythontags
    type: string
